name = "nimpostudioweb"
compatibility_date = "2024-07-01"

[assets]
directory = "./dist"

routes = [
  { pattern = "nimpo3dstudio.com", custom_domain = true },
  { pattern = "www.nimpo3dstudio.com", custom_domain = true },
]